### ISSUE TITLE
Where to find the RC (Raup-Crick index) values in the result files?

### ISSUE THREAD

**Issue by liaochenlanruo** [DaliangNing/NST#1]
As mentioned in the topic.

**Comment by DaliangNing** [comment]
First, you need to set RC=TRUE in the function tNST. The output of tNST is a list, with an element named 'index.pair'. You can find a column named 'RC.ij' in 'index.pair'.

If you set the dist.method="bray", abundance.weighted=TRUE, null.model="PF" and RC=TRUE, the RC.ij is the modified Roup-Crick index based on Bray-Curtis as described in Stegen et al (2013, ISME J, doi:10.1038/ismej.2013.93). If you set the dist.method="jaccard", abundance.weighted=FALSE, null.model="PF" and RC=TRUE, the RC.ij is the modified Roup-Crick index based on Jaccard as reported by Chase et al (2011, Ecosphere, doi:10.1890/es10-00117.1). 

If you are interested in RC based on phylogenetic beta diversity, you may set RC=TRUE in the function pNST.
