### ISSUE TITLE
Null model biased using unbalanced sampling

### ISSUE THREAD

**Issue by dmaurenza** [DaliangNing/NST#2]
Dear Daling Ning

I am using the NST package to get mean RC and NST within treatments in a community, but considering the pool species. However, when building a null model, Vallend et al, 2007 pointed out a bias when the number of samples varies among treatments. For instance, the species composition of the treatment with a higher sample size will largely determine the regional pool, making sites of that treatment appear more similar to the regional pool, which will potentially tend to have lower mean β RC.

To remove this bias, Vellend et al., 2007 suggest that each species’ frequency in the regional pool should be based on the mean of its frequency within each treatment, rather than its overall frequency. In this way, species frequency could be calculated as the mean of means (that is, each species frequency is the mean of means within treatments).

Thus, I ask you if is possible to include a vector in the null model argument to predefined species frequency. Such fixed species frequency could be externally estimated and included in order to null model argument. Alternatively, I believe that the inclusion of a function where overall species frequency is proportional to sample size within treatments would be the best option.

Thanks
Daniel

VELLEND, M., VERHEYEN, K., FLINN, K.M., JACQUEMYN, H., KOLB, A., VAN CALSTER, H., PETERKEN, G., GRAAE, B.J., BELLEMARE, J., HONNAY, O., BRUNET, J., WULF, M., GERHARDT, F. and HERMY, M. (2007), Homogenization of forest plant communities and weakening of species-environment relationships via agricultural land use. Journal of Ecology, 95: 565-573. https://doi.org/10.1111/j.1365-2745.2007.01233.x

**Comment by DaliangNing** [comment]
Thanks for the suggestion. It makes good sense and is doable. I will try to fix it within next week. I plan to add an option to allow input the frequency of each taxon in the regional pool (meta-community).

**Comment by DaliangNing** [comment]
@dmaurenza In NST version 3.1.3, a new option meta.frequency is added to function tNST, to specify occurrence frequency in the regional pool for null model algorithms. The newest version can be downloaded from [/RPackage/AllVersions](https://github.com/DaliangNing/NST/tree/master/RPackage/AllVersions). You may also check step 7.3 in the updated [example](https://github.com/DaliangNing/NST/blob/master/Examples/SimpleOTU/NST.example.r).

**Comment by dmaurenza** [comment]
Thanks Ning.
I haven't accessed my database, but using your "example" it seems to be exactly what I thought.
If you allow me, one more suggestion (which is a simple detail): Why not include RC values ​​in the results of $ index.grp? Today, I'm doing average RC by joing $index.pair.grp (to get pairs for each treatment) with $index.pair (to get RC values), by c(name1, name2), then average calculation.
Daniel

**Comment by DaliangNing** [comment]
In the latest version (3.1.8), summary of SES and RC has been added into functions tNST, pNST, and cNST. Bootstrapping test and PERMANOVA analysis for SES and RC have also been added into functions nst.boot and nst.panova, respectively. Lastest version can be downloaded from https://github.com/DaliangNing/NST/tree/master/RPackage/AllVersions

**Comment by DaliangNing** [comment]
I hope the latest version has solved the problem. If no more problems, I will close this issue soon.

**Comment by dmaurenza** [comment]
Hi Ning.
Yes, your adjusts solved my problems. Thank you very much. .
I will share here when the study is published
Daniel
