### ISSUE TITLE
NST does not range from 0 to 1

### ISSUE THREAD

**Issue by chenyj8** [DaliangNing/NST#4]
Hi Daliang,

In the PNAS paper, you mentioned that NST should range from 0 to 1. However, in my results I found that NST.ij.bray/NST.ij.bMNTD does not range from 0 to 1. The MSTij.bray/MST.ij.bMNTD ranges from 0 to 1, though. Should I use MST instead of NST?

Best,

Chen

**Comment by DaliangNing** [comment]
NST is normalization of ST, and the normalization only ensures the NST of each group (kind of group mean) within the range of [0,1], thus some NSTij can be out of the range and become meaningless in ecology. If you want to get the variation of NST in each group, please use the function nst.boot.

Only if the pairwise values of NST are very important for your research, I suggest using MSTij. In the output of tNST or pNST, you may find MSTij in “index.pair”.  MST is a particular form of NST, and always within the range between 0 and 1. Detailed math of MST was described in Liang et al 2020. Modified stochasticity ratio (MST) can be regarded as a spcial transformation of NST under the assumption that observed similarity can be equal to mean of null similarity under pure stochastic assembly.

Liang Y, Ning D, Lu Z, Zhang N, Hale L, Wu L, Clark IM, McGrath SP, Storkey J, Hirsch PR, Sun B, and Zhou J. (2020) Century long fertilization reduces stochasticity controlling grassland microbial community succession. Soil Biology and Biochemistry 151, 108023. doi:10.1016/j.soilbio.2020.108023.

**Comment by chenyj8** [comment]
Thank you for your clarification.
