### ISSUE TITLE
Regarding the NST model

### ISSUE THREAD

**Issue by Muneer111** [DaliangNing/NST#6]
Dear Prof
I trust you are keeping well
I want to know, that is it necessary to have phylogenetic tree for this model, or we can use this with out tree
kindly please let me know
Thanks and Regards

**Comment by DaliangNing** [comment]
Taxonomic NST (the function tNST) does not need a phylogenetic tree. In the first paper about NST ([https://doi.org/10.1073/pnas.1904623116](https://doi.org/10.1073/pnas.1904623116)), we used tNST based on functional gene microarray data, which has no phylogenetic tree information.
But, for amplicon sequencing data where phylogenetic trees should be available, we found phylogenetic NST results could be more reasonable than taxonomic NST in several studies.

**Comment by lcamVz** [comment]
I have a question, from the multiple outputs of the tNST function how I can go about visualizing the results? from all of the index.pair, index.grp, index.pair.grp, index. between etc.

**Comment by DaliangNing** [comment]
@lcamVz  usually, index.grp is the most important, showing the stochasticity of community assembly in each group of samples. To visualize the results, you usually need to run the function 'nst.boot' to get the statistics (quartiles or all bootstrappin values for box plot) and statistical significance (p values) of the difference of NST in different groups.
